"""
Prompts for the Developer Studio Agent. Currently empty: today's real
capability (streaming already-generated files to the UI) re-broadcasts
content that was already generated by FrontendAgent/BackendAgent -- it
never calls an LLM itself, so there is no prompt yet. Present so the
folder shape matches every other agent; a real prompt will be added here
if/when a future capability (e.g. generated-code review) is implemented.
"""
from __future__ import annotations
