"""
agents/database/agent.py
==========================
Database Agent — the single, production Database Agent implementation for
the platform (consolidated from two prior implementations: this richer,
previously-unwired agents/db_agent.py, and a simpler inline implementation
in ai_service.py that was actually wired into the pipeline). Owns its own
prompts (prompts.py) and schema (schemas.py); the pipeline orchestrator
only ever calls `.generate(...)`.

Consolidation notes (why this file looks the way it does):
  - `generate_schema_and_migrations(ba_output, db_type)` and
    `chat_with_schema(schema_json, user_query)` are DatabaseAgent's
    original, richer, typed methods — unchanged.
  - `.generate(db, project_id, context)` is the NEW orchestrator-facing
    entrypoint that replaces ai_service.generate_database_schema. It
    adapts the pipeline's flat `context` string into a BusinessAnalystOutput
    -shaped input by fetching the project's actual `user_stories`
    GeneratedArtifact (falling back to wrapping the flat context if that
    artifact isn't available yet), then calls
    generate_schema_and_migrations — preserving the existing artifact
    contract (SQL_SCHEMA content as embedded JSON text) so downstream
    agents (UI/UX, Frontend, Backend, Documentation) need no changes.
"""
from __future__ import annotations

import json
from ...logging_config import get_logger
from typing import Any

from ..llm_service import LLMService
from ..business_analyst.schemas import BusinessAnalystOutput
from .prompts import DATABASE_CHAT_PROMPT, DATABASE_SYSTEM_PROMPT
from .schemas import DatabaseSchemaOutput, SchemaChatOutput, SUPPORTED_DB_TYPES

logger = get_logger(__name__)


# ---------------------------------
# Demo-mode fixture (returned only when the deployment-wide DEMO_MODE flag
# is on — see ai_service.py's module docstring for the contract).
# ---------------------------------
MOCK_DATABASE_SCHEMA: dict[str, Any] = {
    "tables": [
        {
            "name": "customers",
            "columns": [
                {"name": "id", "type": "SERIAL", "nullable": False, "primary_key": True},
                {"name": "full_name", "type": "VARCHAR(255)", "nullable": False},
                {"name": "email", "type": "VARCHAR(255)", "nullable": False, "unique": True},
                {"name": "hashed_password", "type": "VARCHAR(255)", "nullable": False},
                {"name": "created_at", "type": "TIMESTAMPTZ", "nullable": False, "default": "now()"},
            ],
            "indexes": ["idx_customers_email"],
        },
        {
            "name": "accounts",
            "columns": [
                {"name": "id", "type": "SERIAL", "nullable": False, "primary_key": True},
                {"name": "customer_id", "type": "INTEGER", "nullable": False, "foreign_key": "customers.id"},
                {"name": "account_number", "type": "VARCHAR(20)", "nullable": False, "unique": True},
                {"name": "account_type", "type": "VARCHAR(20)", "nullable": False},
                {"name": "balance", "type": "NUMERIC(14,2)", "nullable": False, "default": "0"},
                {"name": "currency", "type": "VARCHAR(3)", "nullable": False, "default": "'USD'"},
            ],
            "indexes": ["idx_accounts_customer_id"],
        },
        {
            "name": "transactions",
            "columns": [
                {"name": "id", "type": "SERIAL", "nullable": False, "primary_key": True},
                {"name": "account_id", "type": "INTEGER", "nullable": False, "foreign_key": "accounts.id"},
                {"name": "transaction_type", "type": "VARCHAR(20)", "nullable": False},
                {"name": "amount", "type": "NUMERIC(14,2)", "nullable": False},
                {"name": "description", "type": "VARCHAR(255)", "nullable": True},
                {"name": "occurred_at", "type": "TIMESTAMPTZ", "nullable": False, "default": "now()"},
            ],
            "indexes": ["idx_transactions_account_id", "idx_transactions_occurred_at"],
        },
    ],
    "relationships": [
        {"from_table": "accounts", "to_table": "customers", "type": "one-to-many", "via": None},
        {"from_table": "transactions", "to_table": "accounts", "type": "one-to-many", "via": None},
    ],
    "sql_ddl": """\
-- Generated by Database Agent — Banking Portal Demo
CREATE TABLE customers (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('checking','savings')),
    balance NUMERIC(14,2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD'
);

CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('credit','debit')),
    amount NUMERIC(14,2) NOT NULL,
    description VARCHAR(255),
    occurred_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_customers_email ON customers(email);
CREATE INDEX idx_accounts_customer_id ON accounts(customer_id);
CREATE INDEX idx_transactions_account_id ON transactions(account_id);
CREATE INDEX idx_transactions_occurred_at ON transactions(occurred_at);
""",
    "er_diagram": (
        "erDiagram\n"
        "  CUSTOMERS ||--o{ ACCOUNTS : owns\n"
        "  ACCOUNTS ||--o{ TRANSACTIONS : records\n"
        "  CUSTOMERS {\n    int id PK\n    string full_name\n    string email UK\n    string hashed_password\n    timestamptz created_at\n  }\n"
        "  ACCOUNTS {\n    int id PK\n    int customer_id FK\n    string account_number UK\n    string account_type\n    numeric balance\n    string currency\n  }\n"
        "  TRANSACTIONS {\n    int id PK\n    int account_id FK\n    string transaction_type\n    numeric amount\n    string description\n    timestamptz occurred_at\n  }"
    ),
    "scaling_strategy": "Current volume (<10k transactions/day) sits comfortably on a single PostgreSQL primary. The first scaling lever is a read replica once GET /transactions and GET /accounts read QPS exceeds ~70% of primary capacity — the application already separates read and write paths so routing reads to a replica requires no code changes, only a connection-string swap. Connection pooling (PgBouncer, transaction mode) is added before vertical resizing to avoid connection exhaustion under bursty load. Vertical scaling (larger instance class) is the second lever and covers projected growth for 3-5 years at current trajectory before partitioning becomes necessary.",
    "partitioning_recommendations": "The `transactions` table is the only candidate for partitioning — it's the fastest-growing table and nearly all queries filter by `occurred_at` (transaction history) or `account_id`. Recommend range partitioning by `occurred_at` (monthly partitions) once the table exceeds ~50M rows: this keeps each partition's B-tree index small enough to stay cache-resident and lets old partitions be archived/detached cheaply for data-retention compliance. `customers` and `accounts` are small, slow-growing dimension tables and should NOT be partitioned — partitioning them would add query-planning overhead with no benefit at their scale.",
    "design_decisions": [
        {"decision": "SERIAL (int) primary keys rather than UUIDs",
         "rationale": "This is a single-database system with no multi-region write requirement, so sequential integer keys give smaller indexes and faster joins than UUIDs; UUIDs only pay off when you need globally-unique keys generated client-side or across multiple writers."},
        {"decision": "NUMERIC(14,2) for monetary amounts, never FLOAT",
         "rationale": "Floating point cannot represent currency exactly (rounding errors compound across transactions); NUMERIC is exact and the fixed 2-decimal scale matches standard currency minor units."},
        {"decision": "ON DELETE CASCADE from accounts to customers",
         "rationale": "A deleted customer should not leave orphaned accounts; this is a demo/dev convenience — production would soft-delete (a `deleted_at` column) rather than hard-cascade, to preserve the audit trail required for financial records."},
    ],
}


def build_schema_prompt(
    ba_output: BusinessAnalystOutput | dict,
    db_type: str
) -> str:
    """
    Assembles user prompt instruction payloads matching targeted database options.
    """
    payload = ba_output.model_dump() if hasattr(ba_output, "model_dump") else ba_output

    return f"""
Target Database Type: {db_type}

Business Analyst Output:
{json.dumps(payload, indent=2)}

Generate:
1. Entities
2. Columns
3. Primary Keys
4. Unique Constraints
5. Indexes
6. Relationships
7. Migration Scripts (UP and DOWN)
8. Full SQL DDL
9. Scaling strategy and partitioning recommendations
10. Design decisions, normalization notes, ER diagram, audit tables, sample data

Return valid JSON only.
"""


def build_schema_chat_prompt(
    schema_json: DatabaseSchemaOutput | dict,
    user_query: str
) -> str:
    """
    Formats contextual grounding data maps for relational design review discussions.
    """
    payload = schema_json.model_dump() if hasattr(schema_json, "model_dump") else schema_json

    return f"""
Database Schema:
{json.dumps(payload, indent=2)}

User Query:
{user_query}

Answer based only on the schema.
Return JSON:
{{
    "answer": "string",
    "referenced_tables": ["table1"]
}}
"""


class DatabaseAgent:
    """
    Orchestrates table definition generations, DDL compilation runs,
    and granular analysis dialogues using validated runtime schemas.
    """

    def __init__(self, llm: LLMService | None = None, *, db=None, project_id: int | None = None):
        self.llm = llm or LLMService(db=db, project_id=project_id, role="database")

    def generate_schema_and_migrations(
        self,
        ba_output: BusinessAnalystOutput | dict,
        db_type: str = "PostgreSQL"
    ) -> DatabaseSchemaOutput:
        """
        Translates upstream business user contexts directly into a database layout.
        """

        if not ba_output:
            raise ValueError("Upstream inputs and context components parameters cannot be null or empty.")

        if db_type not in SUPPORTED_DB_TYPES:
            raise ValueError(
                f"Requested database dialect translation targets unsupported by platform runtime options: {db_type}"
            )

        result = self.llm.generate_json(
            system=DATABASE_SYSTEM_PROMPT,
            prompt=build_schema_prompt(
                ba_output=ba_output,
                db_type=db_type
            ),
            schema=DatabaseSchemaOutput,
        )

        if not isinstance(result, DatabaseSchemaOutput):
            raise ValueError("Operational parsing exception encountered: Result failed signature validations checks.")

        if not result.entities:
            raise ValueError("Runtime setup verification warnings: Engine produced zero target data tables.")

        return result

    def chat_with_schema(
        self,
        schema_json: DatabaseSchemaOutput | dict,
        user_query: str
    ) -> SchemaChatOutput:
        """
        Executes granular search validations over historical architecture profiles.
        """

        if not schema_json:
            raise ValueError("Target database architecture configurations contexts cannot be empty.")

        if not user_query.strip():
            raise ValueError("Input conversation user diagnostic string fields cannot be empty or blank.")

        result = self.llm.generate_json(
            system=DATABASE_CHAT_PROMPT,
            prompt=build_schema_chat_prompt(
                schema_json=schema_json,
                user_query=user_query
            ),
            schema=SchemaChatOutput,
        )

        if not isinstance(result, SchemaChatOutput):
            raise ValueError("Operational parsing exception encountered: Result failed chat output signature checks.")

        return result

    @classmethod
    def generate(cls, db, project_id: int, context: str, db_type: str = "PostgreSQL") -> dict[str, Any]:
        """Orchestrator-facing entrypoint: `DatabaseAgent.generate(db, project_id, context)`.
        Adapts the pipeline's flat context string into a BusinessAnalystOutput
        -shaped input (fetching the project's real user_stories artifact when
        available, so the schema is grounded in actual epics/stories rather
        than just prose) and preserves the DEMO_MODE / AIGenerationError
        contract of the previous inline ai_service.generate_database_schema."""
        from ...models import DEMO_MODE, ArtifactType, GeneratedArtifact
        from ...ai_service import AIGenerationError

        if DEMO_MODE:
            return MOCK_DATABASE_SCHEMA

        ba_output: dict[str, Any]
        user_stories_artifact = (
            db.query(GeneratedArtifact)
            .filter(
                GeneratedArtifact.project_id == project_id,
                GeneratedArtifact.artifact_type == ArtifactType.USER_STORIES.value,
            )
            .order_by(GeneratedArtifact.created_at.desc())
            .first()
        )
        if user_stories_artifact is not None:
            try:
                ba_output = json.loads(user_stories_artifact.content)
            except Exception:
                ba_output = {"context": context}
        else:
            ba_output = {"context": context}

        try:
            llm = LLMService(db=db, project_id=project_id, role="database", timeout=170)
            agent = cls(llm=llm)
            result = agent.generate_schema_and_migrations(ba_output=ba_output, db_type=db_type)
            return result.model_dump()
        except Exception as exc:
            logger.error("[DatabaseAgent] generate failed: %s", exc)
            raise AIGenerationError(f"Database schema generation failed: {exc}") from exc
